exercise_type_dict={ "0.1": 'number',
                     "0.2": 'string',
                     "1.1": 'float_list',
                     "1.2": 'cplx_list',
                     "2.1": 'float_list',
                     "2.2": 'float_list',
                     "3.1": 'qubo_sol',
                     "4.1": 'nparray',
                     "5.1": 'qubo_sol',
                     "5.2": 'cplx_list',
                     "5.3": 'intlist',
                     "5.4": 'intlist',
                     "6.1": 'cplx_list',
                     "6.2": 'cplx_list',
                     "6.3": 'cplx_list',
                     "6.4": 'cplx_list',
                     "6.5": 'cplx_list',
                     "6.6": 'cplx_list',
                     "6.7": 'nparray',
                     "6.8": 'nparray',
                     "7.1": 'nparray',
                     "7.2": 'intlist',
                     "7.3": 'float_list',
                     "8.1": 'float_list',
                     "8.2": 'intlist',
                     "8.3": 'intlist',
                     "8.4": 'qubo_sol',
                     "9.1": 'float_list',
                     "9.2": 'float_list',   
                     "9.3": 'intlist',
                     "10.1": 'intlist',
                     "11.1": 'intlist',
                     "12.1": 'intlist'
                    
              }